### ISSUE TITLE
Why the data size used for ChatGPT and Llama2-7B-chat is different?

### ISSUE THREAD

**Issue by WenjinW** [YangLinyi/Supervised-Knowledge-Makes-Large-Language-Models-Better-In-context-Learners#1]
This paper proposes a new method to enhance the performance of large models by utilizing small models, which is very interesting. There is a detail question here: 
- Why do ChatGPT and Llama2-7B-chat need to use data of different sizes? 
- Are these data used to train the ELECTRA-large?

Looking forward to your reply.

**Comment by YangLinyi** [comment]
Hi Wenjin,

Thanks for your interest and sorry for the late reply. ChatGPT and Llama2-7B-chat have significant performance differences in the instruction following ability. Hence, we adopt a filter strategy only to maintain the samples that can be processed properly, which causes the different data sizes of these models.

The in-domain data that has been used to train the ELECTRA-large is the same as the in-context examples conveyed to LLMs.

Hope it helps, if you have any questions, I would be happy to answer them.

Best wishes,
Linyi
